# _config.yml
title: "Atharv's Website"
description: "Welcome to my portfolio and projects"
# remote_theme: pages-themes/cayman@v0.2.0  # Using a pre-built theme from GitHub Pages themes
# plugins:
#   - jekyll-remote-theme
url: "https://Ceasor06.github.io"  # your site URL
baseurl: ""
